version: '3.8'

services:

  api:
    container_name: kiosk_api
    image: evacacela/my-kiosk-api:1.0.1
    restart: always
    environment:
      DB_IP: xxx.xxx.xx.x
      DB_USERNAME: xxx
      DB_PASSWORD: xxx
    ports:
      - "8080:8080"