version: '3.8'

services:

  api:
    container_name: kiosk_api
    image: evacacela/my-kiosk-api:1.2.0-SNAPSHOT
    restart: always
    environment:
      DB_IP: xxx.xxx.xxx.x
      DB_USERNAME: mykiosklocal
      DB_PASSWORD: kk84joRPC5
      DB_NAME: mykiosk
    ports:
      - "8080:8080"