version: '3.8'

services:

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mykiosklocal
      POSTGRES_PASSWORD: kk84joRPC5
      POSTGRES_DB: mykiosk
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mykiosk@local.com
      PGADMIN_DEFAULT_PASSWORD: oe98c7pCr2
    ports:
      - "5050:80"
volumes:
  pgdata:
    external: true
    name:
      mykiosk_pgdata